2021-02-17 22:42:45,937 - app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\aroue\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aroue\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aroue\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\aroue\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\aroue\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aroue\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 89, in predict
    generateWAV(all_predictions, "false")
  File "C:\Users\aroue\Downloads\Documents\@ML\notable-flask\melody.py", line 35, in generateWAV
    audio =  np.hstack(audio)
  File "<__array_function__ internals>", line 5, in hstack
  File "C:\Users\aroue\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
